// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Spendo_Backend.Models;

public partial class RecurringTransaction
{
    public int RecurringId { get; set; }

    public int? UserId { get; set; }

    public int? CategoryId { get; set; }

    public decimal Amount { get; set; }

    public string Description { get; set; }

    public string Type { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public string RecurrenceInterval { get; set; }

    public DateOnly? LastGeneratedDate { get; set; }

    public virtual Category Category { get; set; }

    public virtual User User { get; set; }
}